spring:
  application:
    name: config-client
  cloud:
    config:
#      uri: http://localhost:8888/
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: config-service
  
server:
  port: 8881
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/